nodeLinker: node-modules
enableGlobalCache: false
cacheFolder: ./.yarn/cache
globalFolder: ./.yarn/global
packageExtensions:
  "@commitlint/load@*":
    dependencies:
      "@types/node": "24.10.9"
      "typescript": "5.9.2"
