name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Enable Corepack
        run: corepack enable

      - name: Activate Yarn
        run: corepack prepare yarn@4.0.2 --activate

      - name: Install
        run: corepack yarn install --immutable

      - name: Release Build
        run: corepack yarn release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: comic-scroller-*.zip

      - name: Upload Zip
        uses: actions/upload-artifact@v4
        with:
          name: comic-scroller
          path: comic-scroller-*.zip
